name: 'Tests Counter Action'
description: 'Should motivate to write more tests'
author: 'René Oun'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  coverage-main:
    description: 'Main coverage file'
    required: false
  coverage-branch:
    description: 'Branch coverage file'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
  