name: 'Tests Counter Action'
description: 'Should motivate to write more tests'
author: 'René Oun'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
  