name: 'Tests Counter Action'
description: 'Should motivate to write more tests'
author: 'René Oun'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  coverage-path:
    default: './src/coverage/Chrome Headless/index.html'
    description: 'Path to current coverage files'
    required: false
  main-coverage-path:
    default: './main-coverage.html'
    description: 'Path to Main coverage files'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
  