name: 'Tests Counter Action'
description: 'Should motivate to write more tests'
author: 'René Oun'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  CODE_DIFF:
    description: 'Code diff'
    required: false
  COVERAGE:
    description: 'Coverage'
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
  